---
# Configuration sample file for Jingo (YAML)
application:
  title: Jingo
  repository: './'
  docSubdir: ''
  remote: 'origin'
  pushInterval: 30
  secret:
  git: git
  skipGitCheck: false
  loggingMode: 1
  pedanticMarkdown: true
  gfmBreaks: true
  staticWhitelist: "/\\.png$/i, /\\.jpg$/i, /\\.gif$/i"
authentication:
  google:
    enabled: false
    clientId: 
    clientSecret:
    redirectURL: ''
  github:
    enabled: true 
    clientId: 7a383c35edd76cdc1b3a
    clientSecret: 04ef706254a3433f7a26317098b586e9230f1011
    redirectURL: 'http://localhost:6067/auth/github/callback/'
  local:
    enabled: true
    accounts:
      - username: 'admin'
        passwordHash: '4bf3580737118dd4ccf8a163fb65b38128ef92df'
        email: 'support@letsbossa.com'
features:
  markitup: false
  codemirror: true
server:
  hostname: localhost
  port: 6067
  localOnly: true
  baseUrl: ''
authorization:
  anonRead: true
  validMatches: .+
  emptyEmailMatches: false
pages:
  index: Home
  title:
    fromFilename: true
    fromContent: false
    asciiOnly: false
    lowercase: false
  itemsPerPage: 10
customizations:
  sidebar: _sidebar.md
  footer: _footer.md
  style: _style.css
  script: _script.js

